spring:
  profiles:
    active: dev
    #这里默认是dev ，所以每次查出来都会有个dev
---
server:
  port: 7001

spring:
  profiles: dev
#Eureka配置
eureka:
  instance:
    hostname: eureka7001.com  #Eureka 服务端的实例名称
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己，这里自己就是注册中心，所以不注册自己
    fetch-registry: false #默认是true，设置为true则表示自己为注册中心
    service-url:  #监控页面~
      #单机
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
---
server:
  port: 7004

spring:
  profiles: test
#Eureka配置
eureka:
  instance:
    hostname: eureka7001.com  #Eureka 服务端的实例名称
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己，这里自己就是注册中心，所以不注册自己
    fetch-registry: false #默认是true，设置为true则表示自己为注册中心
    service-url:  #监控页面~
      #单机
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/