spring:
  profiles:
    active: dev
    #这里默认是dev ，所以每次查出来都会有个dev
---
server:
  port: 8001
mybatis:
  type-aliases-package: com.xudi.springcloud.pojo
  mapper-locations: classpath*:mybatis/mapper/*.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true  #驼峰命名
#  com.xudi.springcloud.config-location: classpath:mybatis/mybatis-com.xudi.springcloud.config.xml


spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


#Eurake的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: true #向注册中心注册自己，这个默认就是true
  instance:
    instance-id: springcloud-provider-dept8001  #修改默认status
    prefer-ip-address: true   #显示真实的服务的ip地址，而不是localhost

#配置信息
info:
  app.name: xudi-springcloud
  company.name: xudi.study.com

logging:
  level:
    com.xudi.springcloud.dao: debug
---
server:
  port: 8004
mybatis:
  type-aliases-package: com.xudi.springcloud.pojo
  mapper-locations: classpath*:mybatis/mapper/*.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true  #驼峰命名
#  com.xudi.springcloud.config-location: classpath:mybatis/mybatis-com.xudi.springcloud.config.xml


spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#Eurake的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: true #向注册中心注册自己，这个默认就是true
  instance:
    instance-id: springcloud-provider-dept8001  #修改默认status
    prefer-ip-address: true   #显示真实的服务的ip地址，而不是localhost

#配置信息
info:
  app.name: xudi-springcloud
  company.name: xudi.study.com

logging:
  level:
    com.xudi.springcloud.dao: debug